title = "Cowboy Game"
link = "https://youtu.be/2Xf7HBvicL0"
description = "A cowboy battlegrounds game with a emotes UI!"
tags = ["Roblox Studio", "OOP"]
image = "https://placehold.co/800x600/1a1a1a/FFF?text=Cowboy+Game"
featured = false
