title = "Horse RNG"
link = "https://www.roblox.com/games/136955914362530/Horse-RNG"
description = "breed your horses, unlock rare breeds, and then race them to make money! I built the wandering trader system and did optimization on this project!"
tags = ["Roblox Studio", "OOP", "Rojo"]
image = "https://tr.rbxcdn.com/180DAY-0b1d634a8ac8530f41a72ec94c02e9e0/768/432/Image/Webp/noFilter"
featured = true
