title = "Plate Chaos 2"
link = "https://www.youtube.com/watch?v=ZSR-fwXf7SM"
description = "Successor to one of my first games, still in development!"
tags = ["Roblox Studio", "Hermes"]
image = "https://placehold.co/800x600/1a1a1a/FFF?text=Plate+Chaos+2"
featured = false
