title = "Sword Combat"
link = "https://youtu.be/G7UvieVJyGo"
description = "A basic sword combat system."
tags = ["Roblox Studio", "RaycastHitbox"]
image = "https://placehold.co/800x600/1a1a1a/FFF?text=Sword+Combat"
featured = false
