title = "Tycoon Creator"
link = "https://www.roblox.com/games/99681937282481"
description = "A sandbox tycoon game demo built using Nevermore Engine. Open source on GitHub."
tags = ["Roblox Studio", "Nevermore Engine", "Open Source"]
image = "https://ewe3rn3et5.ufs.sh/f/O2pVoxcml58RChvHEPtAlbWrZYX9vkgKoUzcFnVyetHL5MPQ"
featured = true
